name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Print Flutter version
      run: flutter --version

    - name: Install dependencies (Workspace-wide)
      run: flutter pub get

    # flutterflip_shared
    - name: "[Shared] Format Check"
      run: dart format --output none --set-exit-if-changed packages/flutterflip_shared

    - name: "[Shared] Analyze"
      run: dart analyze --fatal-infos packages/flutterflip_shared

    # flutterflip_server
    - name: "[Server] Format Check"
      run: dart format --output none --set-exit-if-changed packages/flutterflip_server

    - name: "[Server] Analyze"
      run: dart analyze --fatal-infos packages/flutterflip_server

    # flutterflip (Client App)
    - name: "[Client] Format Check"
      run: dart format --output none --set-exit-if-changed packages/flutterflip

    - name: "[Client] Analyze"
      run: flutter analyze --fatal-infos packages/flutterflip

    - name: "[Client] Run Tests"
      working-directory: packages/flutterflip
      run: flutter test
