name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  shared:
    name: "Shared Package"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Print Flutter version
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Format Check
      run: dart format --output none --set-exit-if-changed packages/flutterflip_shared

    - name: Analyze
      run: dart analyze --fatal-infos packages/flutterflip_shared

    - name: Run Tests
      working-directory: packages/flutterflip_shared
      run: dart test

  server:
    name: "Server Package"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Print Flutter version
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Format Check
      run: dart format --output none --set-exit-if-changed packages/flutterflip_server

    - name: Analyze
      run: dart analyze --fatal-infos packages/flutterflip_server

    - name: Run Tests
      working-directory: packages/flutterflip_server
      run: dart test

  client:
    name: "Client App Package"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Print Flutter version
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Format Check
      run: dart format --output none --set-exit-if-changed packages/flutterflip

    - name: Analyze
      run: flutter analyze --fatal-infos packages/flutterflip

    - name: Run Tests
      working-directory: packages/flutterflip
      run: flutter test

  build_and_deploy:
    needs: [ client ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/flutterflip
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web Application
        run: flutter build web --dart-define-from-file=config/app_config.prod.json
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REDBROGDON_DEV }}
          channelId: live
          projectId: redbrogdon-dev