name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  shared:
    name: "Shared Package"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Format Check
      run: dart format --output none --set-exit-if-changed packages/flutterflip_shared

    - name: Analyze
      run: dart analyze --fatal-infos packages/flutterflip_shared

  server:
    name: "Server Package"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Format Check
      run: dart format --output none --set-exit-if-changed packages/flutterflip_server

    - name: Analyze
      run: dart analyze --fatal-infos packages/flutterflip_server

  client:
    name: "Client App Package"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Format Check
      run: dart format --output none --set-exit-if-changed packages/flutterflip

    - name: Analyze
      run: flutter analyze --fatal-infos packages/flutterflip

    - name: Run Tests
      working-directory: packages/flutterflip
      run: flutter test
